version: '2'

services:

### Application Code Container ######################
#此配置默认将同级目录下所有文件映射到数据卷容器applications中
    applications:
        image: tianon/true
        volumes:
            - ${APPLICATION}:/var/www

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
                - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
                - INSTALL_SOAP=${WORKSPACE_INSTALL_SOAP}
                - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
                - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO}
                - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
                - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH}
                - PUID=${WORKSPACE_PUID}
                - PGID=${WORKSPACE_PGID}
                - NODE_VERSION=${WORKSPACE_NODE_VERSION}
                - YARN_VERSION=${WORKSPACE_YARN_VERSION}
                - TZ=${WORKSPACE_TIMEZONE}
            dockerfile: "Dockerfile-${PHP_VERSION}"
        volumes_from:
            - applications
        volumes:
            - ${WORKSPACE_XDEBUG_CONF}:/etc/php/7.2/cli/conf.d/xdebug.ini
            - ${WORKSPACE_CRONTAB}:/etc/cron.d
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        tty: true
        container_name: workspace

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
                - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
            dockerfile: Dockerfile-${PHP_VERSION}
        volumes_from:
            - applications
        volumes:
            - ${PHP_FPM_XDEBUG_CONF}:/etc/php/7.2/cli/conf.d/xdebug.ini
            - ${PHP_FPM_INI_CONF}:/usr/local/etc/php/conf.d/site.ini
            - ${PHP_FPM_POOL_CONF}:/usr/local/etc/php-fpm.d/site.pool.ini
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        container_name: php-fpm

### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./php-worker
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      volumes:
            - ${PHP_WORKER_SUPERVISORD_CONF}:/etc/supervisord.conf
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      container_name: php-worker

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${NGINX_CONF}:/etc/nginx/nginx.conf
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        container_name: php-worker

### MySQL Container #########################################

    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - ${MYSQL_CONF}:/etc/mysql/conf.d/my.cnf
        ports:
            - "${MYSQL_PORT}:3306"
        container_name: mysql


### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"
        container_name: redis

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_HOST_PORT}:11211"
        links:
            - php-fpm
        container_name: memcached

### Elasticsearch Container #######################################

    elasticsearch:
        build: ./elasticsearch
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - elasticsearch-plugins:/usr/share/elasticsearch/data
        ports:
            - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
            - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
        depends_on:
            - php-fpm
        container_name: elasticsearch

### phpMyAdmin Container ##################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: zy
            MYSQL_PASSWORD: zy3910zhang
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            - "${PMA_DB_ENGINE}"
        container_name: phpmyadmin

### MongoDB Container #######################################

    mongo:
      build: ./mongo
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - mongo:/data/db
        




### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    memcached:
        driver: "local"
    redis:
        driver: "local"
    phpmyadmin:
        driver: "local"
    elasticsearch-data:
        driver: "local"
    elasticsearch-plugins:
        driver: "local"
    mongo:
        driver: "local"

